# Generated by Django 3.2.7 on 2023-10-16 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_uservaluehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservaluehistory',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
