# Generated by Django 3.2.7 on 2023-10-17 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20231016_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gain', models.DecimalField(decimal_places=1, max_digits=12)),
                ('total_volume_trades', models.IntegerField(max_length=10)),
                ('total_volume_trades_value', models.IntegerField(max_length=10)),
                ('biggest_winner', models.CharField(max_length=255)),
                ('biggest_loser', models.CharField(max_length=255)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
