# Generated by Django 3.2.7 on 2023-10-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='total_volume_trades',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='total_volume_trades_value',
        ),
        migrations.AddField(
            model_name='userstats',
            name='average_profit_per_trade',
            field=models.DecimalField(
                decimal_places=1, default=1.1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstats',
            name='total_trades',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstats',
            name='total_volume_bought',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstats',
            name='total_volume_bought_value',
            field=models.DecimalField(
                decimal_places=1, default=2, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstats',
            name='total_volume_sold',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstats',
            name='total_volume_sold_value',
            field=models.DecimalField(
                decimal_places=1, default=2.2, max_digits=12),
            preserve_default=False,
        ),
    ]
