# Generated by Django 3.2.7 on 2023-10-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20231017_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastRefresh', models.DateField()),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
