# Generated by Django 3.2.7 on 2023-10-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_itemprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemprice',
            old_name='lastRefresh',
            new_name='last_refresh',
        ),
    ]
