# Generated by Django 3.2.7 on 2023-10-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_lastrefresh_itemprice_last_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprice',
            name='last_refresh',
            field=models.DateTimeField(),
        ),
    ]
