# Generated by Django 3.2.7 on 2023-11-13 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_itemprice_first_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprice',
            name='first_sale_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
