# Generated by Django 3.2.7 on 2023-11-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_itemprice_first_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprice',
            name='last_hundred_day_price',
            field=models.DecimalField(decimal_places=2, default=2.22, max_digits=10),
            preserve_default=False,
        ),
    ]
