# Generated by Django 3.2.7 on 2023-11-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_itemprice_last_hundred_day_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemprice',
            name='last_hundred_day_price',
        ),
    ]
