# Generated by Django 3.2.7 on 2023-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20231120_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='portfolio',
            field=models.CharField(max_length=255),
        ),
    ]
